obj-$(CONFIG_FUNCTION_DURATION_TRACER) += trace_duration.o
obj-$(CONFIG_MTK_TRACER_SAMPLE) += trace_mtk_test.o
obj-$(CONFIG_MT65XX_TRACER) += trace_mt65xx_mon.o
obj-$(CONFIG_HAVE_TCM) += tcm.o
obj-$(CONFIG_CPUTIME_SUPPORT) += cputime_stats.o
