#ifndef __KERNEL_RTPM_PRIO__
#define __KERNEL_RTPM_PRIO__

#define RTPM_PRIO_SWLOCKUP		99
#define RTPM_PRIO_AED			99
#define RTPM_PRIO_WDT			99
#define RTPM_PRIO_PLAYBACK_THREAD	95
#define RTPM_PRIO_SCRN_UPDATE		94
#define RTPM_PRIO_CAMERA_PREVIEW	91
#define RTPM_PRIO_CAMERA_COMPRESS	90
#define RTPM_PRIO_FB_THREAD	 	87
#define RTPM_PRIO_3D_LAYER		86
#define RTPM_PRIO_SURFACEFLINGER	84
#define RTPM_PRIO_SURFACE_OUT		80
#define RTPM_PRIO_OMX_VIDEO		75

#define RTPM_PRIO_RECORD_THREAD		44
#define RTPM_PRIO_AUDIO_IN		43
#define RTPM_PRIO_PV_AUTHOR		42
#define RTPM_PRIO_PV_MP4COMPOSER	41

#define RTPM_PRIO_AUDIO_COMMAND		69
#define RTPM_PRIO_AUDIO_OUT		64
#define RTPM_PRIO_AUDIO_CCCI_THREAD	62
#define RTPM_PRIO_VORBIS_DECODE		92

#define RTPM_PRIO_MIDI_FILE		30
#define RTPM_PRIO_PV_MNTMON		9	
#define RTPM_PRIO_PV_METARETR		8
#define RTPM_PRIO_TPD			4
#define RTPM_PRIO_KSDIOIRQ		1
#define RTPM_PRIO_AUDIOTRACK_THREAD	1

#define RTPM_PRIO_NUM	26

#endif
