AUTO_ADD_GLOBAL_DEFINE_BY_VALUE=CUSTOM_KERNEL_08_LENS CUSTOM_KERNEL_09_LENS CUSTOM_KERNEL_10_LENS CUSTOM_KERNEL_11_LENS CUSTOM_KERNEL_12_LENS CUSTOM_KERNEL_13_LENS CUSTOM_KERNEL_14_LENS CUSTOM_KERNEL_15_LENS CUSTOM_KERNEL_08_IMGSENSOR CUSTOM_KERNEL_09_IMGSENSOR CUSTOM_KERNEL_10_IMGSENSOR CUSTOM_KERNEL_11_IMGSENSOR CUSTOM_KERNEL_12_IMGSENSOR CUSTOM_KERNEL_13_IMGSENSOR CUSTOM_KERNEL_14_IMGSENSOR CUSTOM_KERNEL_15_IMGSENSOR

#
# MTK Build Info
#

MTK_AUD_LOCK_MD_SLEEP_SUPPORT=no
MTK_ANR_SUPPORT=no

MTK_BRANCH = ALPS.GB2.MP
	# Depend on branch

MTK_BUILD_VERNO = ALPS.GB2.MP.V2.24
	# Depend on release week

MTK_WEEK_NO =  
	# Depend on release week

# for build verno customization
CUSTOM_BUILD_VERNO =

# using customization key/cert. for app. signing
MTK_SIGNATURE_CUSTOMIZATION = no

# BICR (Build in CD ROM) -- Cui Zhang (83154)
MTK_BICR_SUPPORT=no

# Enlai Chu (83167)
MTK_CNN_CBN=no

MTK_2SDCARD_SWAP = no

MTK_S3D_SUPPORT = no

# merge MTK critical patch by ruifeng.dong for ALPS00450714

MTK_SEND_RR_SUPPORT = no

MTK_FAT_ON_NAND  = no

MTK_BT_POWER_EFFICIENCY_ENHANCEMENT = yes

MTK_NOTEBOOK_SUPPORT=no

MTK_MVNO_SUPPORT=no

MTK_PRODUCT_INFO_SUPPORT=no

MTK_REMOVE_H264_LEVEL_LIMIT=yes

MTK_RMVB_PLAYBACK_SUPPORT=no

MTK_DATAREG_APP = no

CUSTOM_HAL_08_LENS = 
CUSTOM_HAL_09_LENS = 
CUSTOM_HAL_10_LENS = 
CUSTOM_HAL_11_LENS = 
CUSTOM_HAL_12_LENS = 
CUSTOM_HAL_13_LENS = 
CUSTOM_HAL_14_LENS = 
CUSTOM_HAL_15_LENS = 

CUSTOM_HAL_08_IMGSENSOR = 
CUSTOM_HAL_09_IMGSENSOR = 
CUSTOM_HAL_10_IMGSENSOR = 
CUSTOM_HAL_11_IMGSENSOR = 
CUSTOM_HAL_12_IMGSENSOR = 
CUSTOM_HAL_13_IMGSENSOR = 
CUSTOM_HAL_14_IMGSENSOR = 
CUSTOM_HAL_15_IMGSENSOR = 

CUSTOM_KERNEL_08_LENS = 
CUSTOM_KERNEL_09_LENS = 
CUSTOM_KERNEL_10_LENS = 
CUSTOM_KERNEL_11_LENS = 
CUSTOM_KERNEL_12_LENS = 
CUSTOM_KERNEL_13_LENS = 
CUSTOM_KERNEL_14_LENS = 
CUSTOM_KERNEL_15_LENS = 

CUSTOM_KERNEL_08_IMGSENSOR = 
CUSTOM_KERNEL_09_IMGSENSOR = 
CUSTOM_KERNEL_10_IMGSENSOR = 
CUSTOM_KERNEL_11_IMGSENSOR = 
CUSTOM_KERNEL_12_IMGSENSOR = 
CUSTOM_KERNEL_13_IMGSENSOR = 
CUSTOM_KERNEL_14_IMGSENSOR = 
CUSTOM_KERNEL_15_IMGSENSOR = 
MTK_IPV6_SUPPORT = yes
