#EXTRA_CFLAGS += -O3
obj-m += gt818_downloader.o
#mt6516-tpd-objs += \
#    custom/build/driver.o \
#    custom/build/tpd_button.o \
#    custom/build/tpd_debug.o \
#    custom/build/tpd_default.o \
#    custom/build/mt6516_tpd.o \
#    custom/build/tpd_calibrate.o \
#    custom/build/tpd_init.o
#ccflags-y += -Idrivers/input/touchscreen/mt6516/custom/build
